version: "3.3"

services:
  # 1. Base de Datos
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=ports
    volumes:
      - influx-data:/var/lib/influxdb

  # 2. TU APP UNIFICADA (Frontend + Backend + Sniffer)
  app_forense:
    build: .
    container_name: monitor-app-full
    network_mode: "host"      # Obligatorio para capturar tráfico real
    depends_on:
      - influxdb

  # 3. SIMULADOR (Comentado para la entrega final)
  # simulator:
  #   build: ./simulator
  #   container_name: monitor-simulator
  #   depends_on:
  #     - influxdb
# 3. SCANNER DEL COMPAÑERO (Auditoría de Vulnerabilidades)
  cve_scanner:
    build:
      context: ./cve/cve_scanner
      dockerfile: Dockerfile
    container_name: cve_scanner
    ports:
      - "9000:9000"
    volumes:
      - ./cve/cve_scanner/output:/app/output
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - internal_net

  # 4. FRONTEND DEL COMPAÑERO (RUTA CORREGIDA)
  cve_frontend_v2:
    build:
      context: ./cve/cve_scanner/frontend  # <--- Cambiado de scanner_frontend a frontend
      dockerfile: Dockerfile               # <--- Esto asume que hay un Dockerfile dentro de esa carpeta
    container_name: cve_frontend
    ports:
      - "5173:5173"
    depends_on:
      - cve_scanner
    networks:
      - internal_net
#
networks:
  internal_net:
    driver: bridge

volumes:
  influx-data:
