version: "3.3"

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    network_mode: "host"
    environment:
      - INFLUXDB_DB=ports
    volumes:
      - influx-data:/var/lib/influxdb

  app_forense:
    build: .
    container_name: monitor-app-full
    network_mode: "host"
    privileged: true
    depends_on:
      - influxdb

  cve_scanner:
    build:
      context: ./cve/cve_scanner
      dockerfile: Dockerfile
    container_name: cve_scanner
    privileged: true
    network_mode: "host"
    volumes:
      - ./cve/cve_scanner/scanner_backend/output:/app/output
      - /proc:/proc
      - /sys:/sys
      - /dev:/dev

  cve_frontend:
    build:
      context: ./cve/cve_scanner/scanner_frontend
      dockerfile: Dockerfile
    container_name: cve_frontend
    network_mode: "host"
    depends_on:
      - cve_scanner

volumes:
  influx-data:
  # 3. SIMULADOR (Comentado para la entrega final)
  # simulator:
  #   build: ./simulator
  #   container_name: monitor-simulator
  #   depends_on:
  #     - influxdb
