services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cve_scanner_backend
    privileged: true
    network_mode: "host"     # 🔥 Tu backend ahora usa la red real del host
    volumes:
      - ./scanner_backend/output:/app/output
      - /proc:/proc
      - /sys:/sys
      - /dev:/dev
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # ❌ Ya no necesitas ports ni networks aquí

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cve_scanner_server
    privileged: true
    volumes:
      - ./scanner_backend/output:/app/output
      - /proc:/proc
      - /sys:/sys
      - /dev:/dev
    networks:
      - cve_net
    # 🔎 Este contenedor NO necesita host-mode porque no captura tráfico

  frontend:
    build:
      context: ./scanner_frontend
      dockerfile: Dockerfile
    container_name: cve_scanner_frontend
    ports:
      - "5173:5173"
    networks:
      - cve_net
    # 🔥 Tu frontend sigue en red interna, pero debe llamar a http://localhost:9000

networks:
  cve_net:
